name: inventario_movil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.0
  flutter_secure_storage: ^7.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # Aquí activamos los assets TU carpeta es assets/img/
  assets:
    - assets/img/FONDO-USER2.jpg

  # Si en el futuro agregas fuentes:
  # fonts:
  #   - family: ...
  #     fonts:
  #       - asset: ...
