sonar.projectKey=proyecto_final
sonar.projectName=Proyecto Final
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_8d25f5342764967eaf3abfe735bd25a0fb30760c

sonar.sourceEncoding=UTF-8

# Analiza backend + frontend
sonar.sources=API REST,WEB

# Excluir basura pesada
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.scannerwork/**

# (Opcional) si quieres solo código fuente y no todo:
# sonar.inclusions=API REST/src/**,WEB/src/**
